name: cyberpong
services:
  webserver:
    build: ./webserver
    restart: unless-stopped
    volumes:
      - ./webserver/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./webserver/ssl/:/etc/ssl
    ports:
      - '8080:80'
      - '4443:443'
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../srcs/frontend/:/workspace

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../srcs/backend/:/workspace
    depends_on:
      - database
    ports:
      - 3333:3333

  database:
    build: ./database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
