name: cyberpong
services:
  # webserver:
  #   build: ./webserver
  #   restart: unless-stopped
  #   volumes:
  #     - ./webserver/config/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./webserver/ssl/:/etc/ssl
  #   ports:
  #     - '8080:80'
  #     - '4443:443'
  #   depends_on:
  #     - frontend
  #     - backend

  frontend:
    build: ./frontend
    container_name: cyberpong-frontend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../srcs/frontend/:/workspace
    ports:
      - '127.0.0.1:8080:8080'

  backend:
    build: ./backend
    container_name: cyberpong-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../srcs/backend/:/workspace
    depends_on:
      - database
    ports:
      - 127.0.0.1:3333:3333

  database:
    build: ./database
    container_name: cyberpong-db
    restart: unless-stopped
    env_file:
      - .env
